### PR TITLE
Youtube demo project in HTML and CSS

### PR DESCRIPTION
**Pull request by java-cromium**
Updated the Readme.md in order to make it more descriptive. Added video thumbnail as well and added screen shot as well

### CODE REVIEW

**Review by rOluochKe — COMMENTED** [review]
### Under review...

**Review by rOluochKe — CHANGES_REQUESTED** [review]
@java-cromium and @Tahirbhalli 
### Good job you have done this far, however, there are some changes you need to make for your project to be approved

- Write a more detailed readme file [check this guide](https://github.com/microverseinc/readme-template)
- Validate your index file and solve the errors [check this guide](https://validator.w3.org/#validate_by_upload)
- Write a more detailed pull request on what you have done on the project [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- add .gitignore file in the root folder to prevent files such .DS_Store from being pushed remotely [checkguide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

- You can always reach for help from slack channel, your team, mentor and any TSE
### After making the changes, resubmit the project for review. All the best in the next submission.

**Comment by fatymahmed** [comment]
> Fixed structure and made final changes to the YouTube Channel project.
Hi @java-cromium @Tahirbhalli, please update this section what you have done so far, this is the pull request description section :)

**Review by fatymahmed — APPROVED** [review]
## Hi @java-cromium  @Tahirbhalli,
Great job making changes as requested by the previous reviewer.
It's a 👍🏾 from me!
## ✔️ Approved!

Please make the following changes before merging your pull request
- I'm sorry but just realized that I made a mistake and missed out on **a very important requirement,** please remove the DS_Store file from your committed files as mentioned on [pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png), you can do this by adding it to the .gitignore file and deleting it from your committed files. I **highly recommend** you to do this before you merge your pull request.
- I noticed that you added a detailed description of what you have implemented so far, please put this in the description section of the pull request.
Move the content of the red box to the blue box (this is the description box)
screenshot(3)

[OPTIONAL]
- Your README file is detailed but I suggest you make the syntax look much better, check [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) out on markdown syntax.
- Add a live link of your website in your README file, you can use [this](https://raw.githack.com/) to generate a live link.
- You added stickler in your project, it's not required but great job adding it. Please fix the errors given by stickler.
- I highly encourage you to use the `<main>` tag for the dominant content of the `<body>` of a document.

Good luck with your next projects.
_Don't forget to submit your project completion form_

**Pull request merged**
